### ISSUE TITLE
complite ms office provision

### ISSUE THREAD

**Issue by Iv-Alex** [mpk-it/Administration#16]
- [x] [send mail the get infirmation](https://github.com/orgs/mpk-it/projects/1#card-57764223)
- [x] create list
- [x] get score to buy
- [x] consider office byu organization "tis" and "softline"
- [x] to buy
- [x] install
- [x] rejoise
- [x] add mail signes

**Comment by AlexVlan** [comment]
send mail the get infirmation

**Comment by AlexVlan** [comment]
Бухгалтерия: Камнева, Луговских, Степанова, Никитина.
Реализация: Мастер(Татаринова\Шестакова), Агафонова
