### ISSUE TITLE
Проект видеонаблюдения на ММО

### ISSUE THREAD

**Issue by Iv-Alex** [mpk-it/Administration#20]
- [x] [Create MMO cameras plan current/future](https://github.com/orgs/mpk-it/projects/2#card-57167533)
- [x] [get in the production departament camera layout](https://github.com/mpk-it/Administration/issues/191)
- [x] [create list with necessary material](https://github.com/orgs/mpk-it/projects/1#card-57505967)
- [x] [request aninvoice from "айтиза" purchase invoice](https://github.com/orgs/mpk-it/projects/1#card-57658250)
- [x] [request aninvoice from "ТИС" purchase invoice](https://github.com/orgs/mpk-it/projects/1#card-57658192)
- [x] [to approve contract with "aitiza"]
- [x] [29.03 tranffer for payment](https://github.com/orgs/mpk-it/projects/1#card-57664427)
! STOPPED

**Comment by AlexVlan** [comment]
![IT20210322090143_002](https://user-images.githubusercontent.com/67640029/111952144-bef0ba00-8af5-11eb-8618-fbce772c3108.jpg)
