### ISSUE TITLE
Инвентаризация + светофор

### ISSUE THREAD

**Issue by Iv-Alex** [mpk-it/Administration#27]
- [x] Разбить Мишин файлик по областям
- [x] Определить единое место хранения информации для сбора (vlan) Мишин_Файлег (на момент инвентаризации. Далее - 1С)
- [x] Собрать информацию: инвентарники + PC + пользователь + *офис
- [x] передать Сереже
- [x] собрать список сетевой техники intellect
- [x] получить инвентарники
- [x] нанести полученные от Сережи инвентарники на технику
- [x] формируем актуализацию в Vlan.xls из отчета 1С
- [x] создаем задачу светофор
- [x] create task to network device
- [x] old district inventarisation

Получить инв на эти позиции intellect
- [x] шт-1 1.1____-16______D-link DGS 3620-28SC_       K000288
- [x] шт-1 1.2____-16______D-link DGS 1210-28P_         K000287
- [x] шт-1 1.3____-16______D-link DGS 1210-28P_        K000286
- [x] шт-2 1.4____-185_____D-link DGS 1210-28P_        К000537                  S30R1G5000241
- [x] шт-2 1.5____-185_____D-link DGS 1210-28P_        К000538                  S30R1G5000240
- [x] шт-3 1.6____-113_____D-link DGS 1210-28P_        К000539                  S30R1G5000271
- [x] шт-3 1.7____- 113____D-link DGS 1210-28P_        К000540                  S30R1G5000272
- [x] шт-4 1.8____- 159____D-link DGS 1210-28P_        К000541                  S30R1G5000270
- [x] шт-4 1.12__- 159_____D-link DGS 1210-28P_        К000542
- [x] шт-5 1.9     - КПП1___D-link DGS 1210-28P_       К000543                  S30R1G40001492
- [x] Zebra master kolb K000536 add

**Comment by Iv-Alex** [comment]
blob:file:///f8e53116-33a0-4100-b5be-29c38d02385a

**Comment by AlexVlan** [comment]
make/inficted

**Comment by AlexVlan** [comment]
Получить инв на эти позиции intellect
-[ ] main 1.1
-[ ] шт-1 1.2
-[ ] шт-1 1.3
-[ ] шт-2 1.4
-[ ] шт-2 1.5
-[ ] шт-3 1.6
-[ ] шт-3 1.7
-[ ] шт-4 1.8
-[ ] шт-4 1.12
-[ ] шт-5 1.9
